version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: java_app
    environment:
      JDBC_URL: jdbc:mysql://db:3306/your_database
      DB_USERNAME: admin
      DB_PASSWORD: admin_password
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: